export const ADD_GAMING_DEVICES_FROM_SERVER = "ADD_GAMING_DEVICES_FROM_SERVER"
export const FILTERS_FOR_CATALOG_CATEGORY = "FILTERS_FOR_CATALOG_CATEGORY"
export const DELETE_FILTER_FOR_CATALOG = "DELETE_FILTER_FOR_CATALOG"
export const FILTERS_FOR_CATALOG_BRAND = "FILTERS_FOR_CATALOG_BRAND"
export const DELETE_FILTER_FOR_CATALOG_BRAND = "DELETE_FILTER_FOR_CATALOG_BRAND"
export const SET_SELECTED_DEVICE = "SET_SELECTED_DEVICE"
export const ADD_TO_CHEACKOUT = "ADD_TO_CHEACKOUT"
export const FILTRED_BY_PRICE_DEVICE = "FILTRED_BY_PRICE_DEVICE"
export const ADDONE_PURCHASE_COUNT = "ADDONE_PURCHASE_COUNT"
export const MINUSONE_PURCHASE_COUNT = "MINUSONE_PURCHASE_COUNT"
export const INTOZERO_PURCHASE_COUNT = "INTOZERO_PURCHASE_COUNT"
export const SET_DRAGS_IS_ACTIVE = "SET_DRAGS_IS_ACTIVE"


